defaults:
  - base

model:
  name: pinf
  ic_encoder:
    channels: [32, 64, 64]
    kernel: 5
    latent_dim: 128
  encoding:
    type: siren
    omega_0: 30.0
  trunk:
    hidden_dim: 128
    n_layers: 6
    activation: tanh
